services:
  - type: web
    name: django-music-app
    env: python
    buildCommand: ""
    startCommand: gunicorn music_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: music_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
